### ISSUE TITLE
Hyper-parameters for TOX-171 and COLON datasets

### ISSUE THREAD

**Issue by SilenceX12138** [jcyang34/lspin#2]
Hi!

Thanks for the fantastic work. The results are really reasonable and clear. I have been trying to reproduce the results on TOX-171 and COLON with the code, but the optuna took too long to get the same results as published. Could you please provide the hyper-parameters of LSPIN/LLSPIN on TOX-171 and COLON datasets?

So many thanks for your kind help!

**Comment by jcyang34** [comment]
Thanks for your interest! I put them under real-world-params/ folder.

To clarify, unlike other datasets, I didn't apply Optuna to those 2 datasets because the sample size is too small, as mentioned in the appendix section B. These hyper-parameters are also included there.

**Comment by orItach** [comment]
Hi! 
Thanks you very much for the COLON and TOX-171 hyper-parameters, 
it's help me a lot to reproduce the result after i'm done it on BASEHOCK dataset. 
Unfortunately even with the hyper-parameters i'm couldn't reproduce the TOX-171 result.
The hyper-parameters for COLON work perfect!
At the hyper-parameters for TOX-171 it's give result of 0.5, 
after some tunning the hyper-parameters it's seems need 20,000 epoch 
(about 3 times the 7000 you write at the hyper-parameters) to get good result, about 0.8.
Can you double check the hyper-parameters?
@SilenceX12138 you successfully reproduce the result on TOX-171 with the hyper-parameters?

**Comment by jcyang34** [comment]
see #3
